---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: vmware_fusion
lint:
  name: yamllint
platforms:
  - name: nameserver
    box: inz-sysadmins/ubuntu-bionic
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", disabled: true'
provisioner:
  name: ansible
  config_options:
    connection:
      pipelining: true
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
