---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Disable goofy update
      raw: systemctl stop apt-daily
      become: true
      changed_when: false
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: true
      changed_when: false
